/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.com.amecodelab;

public class App {

    public static void main(String[] args) {
        System.out.println(new App().getOccurrences(new int[]{1, 2, 2, 3, 3, 3, 4, 5, 5}, 5));
    }

    public int getOccurrences(int[] list, int number) {
        if(number > list[list.length -1] || number < list[0]) {
            return 0;
        }

        int smaller = list[0];
        int greatest = list[list.length -1];
        if ((greatest - number) < (number - smaller)) {            
            return getOccurrencesBack(list, number);
        } else {
            return getOccurrencesForward(list, number);
        }
    }

    private int getOccurrencesForward(int[] list, int number) {
        int occurrences = 0;
        for (int i = 0; i < list.length; i++){
            if(list[i] > number) {
                break;
            }

            if(number == list[i]) {
                occurrences++;
            }                
        }

        return occurrences;
    }

    private int getOccurrencesBack(int[] list, int number) {
        int occurrences = 0;
        for (int i = (list.length - 1); i > 0; i--) {
            if(number > list[i]) {
                break;
            }

            if(number == list[i]) {
                occurrences++;
            }                
        }

        return occurrences;
    }
}
