/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.com.amecodelab;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;

class AppTest {

    @Test 
    @DisplayName("when number is not into the array, it should return 0 occurrences")
    void numberIsNotIntoArray() {
        App classUnderTest = new App();
        assertEquals(0, classUnderTest.getOccurrences(new int[]{1, 2, 2, 3, 3, 3, 4, 5, 5}, 6));
    }

    @Test 
    @DisplayName("when number is 5, it should return 2 occurrences")
    void numberIsFiveIntoArray() {
        App classUnderTest = new App();
        assertEquals(2, classUnderTest.getOccurrences(new int[]{1, 2, 2, 3, 3, 3, 4, 5, 5}, 5));
    }

    @Test 
    @DisplayName("when number is three, it should return 4 occurrences")
    void numberIsThreeIntoArray() {
        App classUnderTest = new App();
        assertEquals(4, classUnderTest.getOccurrences(new int[]{1, 2, 2, 3, 3, 3, 3, 4, 5, 5}, 3));
    }

    @Test 
    @DisplayName("when number is one, it should return 1 occurrences")
    void numberIsOneIntoArray() {
        App classUnderTest = new App();
        assertEquals(1, classUnderTest.getOccurrences(new int[]{1, 2, 2, 2, 3, 3, 3, 3, 4, 5, 5}, 1));
    }

    @Test 
    @DisplayName("when number is two, it should return 3 occurrences")
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertEquals(3, classUnderTest.getOccurrences(new int[]{1, 2, 2, 2, 3, 3, 3, 3, 4, 5, 5}, 2));
    }
}
